---
services:
  backend:
    build:
      context: backend
      dockerfile: Dockerfile
      additional_contexts:
        metadata: .
    tty: true
    command: ["fastapi", "run", "./hello.py", "--root-path", "/api"]

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: prod
      additional_contexts:
        metadata: .
    ports:
      - "127.0.0.1:80:80"
    volumes:
      - ./frontend:/app
      - ./node_modules:/app/node_modules
    tty: true
    depends_on:
      - backend
