---
services:
  backend:
    build:
      context: backend
      dockerfile: Dockerfile
      additional_contexts:
        metadata: .
    environment:
      ENV: demo
      LOG_LEVEL: DEBUG
      FRONTEND_URL: localhost:3000
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      additional_contexts:
        metadata: .
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - ./node_modules:/app/node_modules
    tty: true
    depends_on:
      - backend

  nginx:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      additional_contexts:
        metadata: .
    volumes:
      - ./frontend/build:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    tty: true
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend
