---
name: order-up

services:
  backend:
    build:
      context: backend
      dockerfile: Dockerfile
      additional_contexts:
        metadata: .
    ports:
      - "127.0.0.1:8000:8000"
    environment:
      ENV: demo
      LOG_LEVEL: DEBUG
      FRONTEND_URL: localhost:3000

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
      args:
        REACT_APP_BACKEND_DOMAIN: localhost:8000
      additional_contexts:
        metadata: .
    ports:
      - "127.0.0.1:3000:3000"
    volumes:
      - ./frontend:/app
      - ./nginx.dev.conf:/etc/nginx/conf.d/default.conf:ro
    tty: true
    depends_on:
      - backend

  prometheus:
    build:
      context: ./prometheus
      dockerfile: Dockerfile
    ports:
      - "127.0.0.1:9090:9090"
    volumes:
      - prometheus-data:/prometheus

volumes:
  prometheus-data:
