---
name: order-up

services:
  backend:
    image: ghcr.io/capstone-projects-2025-spring/order-up-backend:main
    tty: true
    command: ["fastapi", "run", "./hello.py", "--root-path", "/api"]
    environment:
      ENV: prod
      LOG_LEVEL: WARNING
      FRONTEND_URL: "https://bankruptcyassociation.com"

  frontend:
    image: ghcr.io/capstone-projects-2025-spring/order-up-frontend:main
    tty: true
    depends_on:
      - backend
    ports:
      - "0.0.0.0:80:80"
      - "0.0.0.0:443:443"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro

  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      # 1 minute
      WATCHTOWER_POLL_INTERVAL: 60
      # clean up old image
      WATCHTOWER_CLEANUP: true
      WATCHTOWER_LOG_LEVEL: warn
      WATCHTOWER_LOG_FORMAT: json

  prometheus:
    image: ghcr.io/capstone-projects-2025-spring/order-up-prometheus:main
    volumes:
      - prometheus-data:/prometheus

volumes:
  prometheus-data:
