---
services:
  backend:
    build:
      context: backend
      dockerfile: Dockerfile
      additional_contexts:
        metadata: .
    ports:
      - "8000:8000"
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    depends_on:
      - backend
