---
services:
  backend:
    build:
      context: backend
      dockerfile: Dockerfile
      additional_contexts:
        metadata: .
    environment:
      ENV: demo
      LOG_LEVEL: DEBUG
      FRONTEND_URL: localhost:8000

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: prod
      additional_contexts:
        metadata: .
    ports:
      - "0.0.0.0:80:80"
    volumes:
      - ./frontend:/app
      - ./node_modules:/app/node_modules
    tty: true
    depends_on:
      - backend
