openapi: 3.1.0
info:
  title: AAC Team Sec2 - API Docs
  description: This API controls basic lobby functionality of the AAC game
paths:
  /lobby:
    post:
      summary: Create Lobby
      description: Creates a new lobby, returning lobby code.
      operationId: lobby_post
      responses:
        '201':
          description: Successful Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: string
                    example: Fish-Turtle-Shark
  /lobby/{code}:
    post:
      summary: Join Lobby
      description: Joins a player to a lobby by its unique game code, returning new player information and player avatars.
      operationId: lobby_code_post
      parameters:
      - name: code
        in: path
        required: true
        schema:
          type: string
          title: Code
          description: Lobby Code
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  self:
                    type: object
                    properties:
                      avatar:
                        type: string
                        example: Fish
                      uuid:
                        type: string
                        example: 3e6b52bf-23ae-4f50-ba84-ad35ed1df31b
                  players:
                    type: array
                    example:
                      - Shark
                      - Turtle
                      - Fish
        '404':
          description: Lobby Not Found
  /ws/:
    get:
      summary: Websocket Connection
      description: Handles a WebSocket connection for receiving and responding to messages.
