openapi: 3.1.0
info:
  title: AAC Team Sec2 - API Docs
  description: This API controls basic lobby functionality of the AAC game
paths:
  /lobby:
    post:
      summary: Create Lobby
      description: Creates a new lobby, returning lobby code.
      operationId: lobby_post
      responses:
        '201':
          description: Successful Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: array
                    example:
                      - Patty
                      - Cheese
                      - Tomato
  /lobby/join:
    post:
      summary: Join Lobby
      description: >-
        Joins a player to a lobby by its unique game code, returning new player
        information.
      operationId: lobby_code_post
      requestBody:
        description: Lobby Code
        content:
          application/json:
            schema:
              type: object
              properties:
                code:
                  type: array
                  example:
                    - Patty
                    - Cheese
                    - Tomato
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    example: 3e6b52bf-23ae-4f50-ba84-ad35ed1df31b
        '404':
          description: Lobby Not Found
  /ws/:
    get:
      summary: Websocket Connection
      description: >-
        Handles a WebSocket connection for receiving and responding to messages.
        For more information see Websocket schema.
components: {}
